naam = input("Naam: ")
adres = input("Adres: ")
postcode = input("Postcode: ")
woonplaats = input("Woonplaats: ")

print(" ----------------------------------------------------")
print("|  Naam      : " + naam)
print("|  Adres     : " + adres)
print("|  Postcode  : " + postcode)
print("|  Woonplaats: " + woonplaats)
print(" ----------------------------------------------------")